version: '3.8'

services:
  # Serviço 1: O Banco de Dados SQL Server Express
  db_sql_express:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meu-banco-sql-express
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
      SA_PASSWORD: 'SuaSenhaForte_123' # Senha complexa obrigatória!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  # Serviço 2: Sua API .NET
  api:
    container_name: my-api # <-- MUDANÇA 1 (Opcional, mas limpo)
    build:
      # 'context' é o caminho para a pasta onde está seu Dockerfile
      context: ./my-api  # <-- MUDANÇA 2 (Obrigatória)
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db_sql_express;Database=minha_api_db;User Id=sa;Password=SuaSenhaForte_123;TrustServerCertificate=True;"
    depends_on:
      - db_sql_express

volumes:
  mssql_data: